# Generated by Django 5.0.14 on 2026-06-23 02:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_record_user_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='administrator',
            field=models.ForeignKey(blank=True, limit_choices_to={'profile__role': 'Administrador'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_appointments', to=settings.AUTH_USER_MODEL),
        ),
    ]
